### ISSUE TITLE
this file doesn't appear to exist in the repository

### ISSUE THREAD

**Issue by forensicgarlic** [Xilinx/HLS_packet_processing#2]
This packetRecorder.h file doesn't appear to exist in the repository, nor does it seem to be in my install of 2018.3 
https://github.com/Xilinx/HLS_packet_processing/blob/b165e2adac64dd23a3f1b06ae8b5b7d3672edcbd/apps/arp/app.h#L51

**Comment by stephenneuendorffer** [comment]
Thanks for pointing that out.  It's a bit of archeology that I didn't catch.  Fixed now.
